WebStepBlog/Controllers/CommentsController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebStepBlog.Models;

namespace WebStepBlog.Controllers
{
    public class CommentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Comments/CreateComment/5

        public ActionResult CreateComment(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = GetPost(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        private Post GetPost(int? id)
        {
            return id.HasValue ? db.Posts.Include(p => p.Author).Include(t=>t.Tags).Where(x => x.Id == id).First() : new Post { Id = -1 };
        }

        // POST: Comments/Create/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult AddComment([Bind(Include = "Id,Name,Email,Body")] Comment comment, int postId)
        {
            if (ModelState.IsValid)
            {
                var post = db.Posts.Find(postId);
                Comment inputComment = new Comment();
                inputComment.Body = comment.Body;
                if (User.Identity.IsAuthenticated)
                {
                    string user = User.Identity.GetUserId();
                    ApplicationUser currentUser = db.Users.FirstOrDefault(u => u.Id == user);
                    inputComment.Name = currentUser.UserName;
                    inputComment.Email = currentUser.Email;
                    inputComment.User = db.Users.FirstOrDefault(u => u.UserName == User.Identity.Name);
                }
                else
                {
                    inputComment.Name = comment.Name;
                    inputComment.Email = comment.Email;
                }
                post.Comments.Add(inputComment);
                db.SaveChanges();
                return RedirectToAction("CreateComment", new { id = postId });
            }
            return View("CreateComment", comment);
        }

        // GET: Comments/EditComment/5
        [Authorize(Roles = "Administrators")]
        public ActionResult EditComment(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // POST: Comments/EditComment/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Administrators")]
        [ValidateAntiForgeryToken]
        public ActionResult EditComment([Bind(Include = "Id,Name,Email,Body")] Comment comment, int id)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            return View(comment);
        }

        // GET: Comments/DeleteComment/5
        [Authorize(Roles = "Administrators")]
        public ActionResult DeleteComment(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // POST: Comment/DeleteComment/5
        [Authorize(Roles = "Administrators")]
        [HttpPost, ActionName("DeleteComment")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteComment(int id)
        {
            Comment comment = db.Comments.Find(id);
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
    }
}

WebStepBlog/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebStepBlog.Models;
using PagedList;
using PagedList.Mvc;

namespace WebStepBlog.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index(int? page)
        {
            List<object> sumModel = new List<object>();
            sumModel.Add(db.Posts.Include(p => p.Author).Include(p=>p.Tags).OrderByDescending(p => p.Date).ToList().ToPagedList(page ?? 1, 5));
            sumModel.Add(db.Posts.OrderByDescending(d => d.Date).ToList());
            sumModel.Add(db.Tags.OrderByDescending(d => d.Posts.Count).ToList());
            return View(sumModel);
        }

        public ActionResult Contact()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

    }
}

WebStepBlog/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebStepBlog.Models;
using PagedList;
using PagedList.Mvc;
using WebStepBlog.Extensions;

namespace WebStepBlog.Controllers
{
    [ValidateInput(false)]
    public class PostsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Posts
        public ActionResult Index(int? page)
        {
            var posts = db.Posts.Include(p => p.Author).Include(p => p.Tags).ToList().ToPagedList(page ?? 1, 5);
            return View(posts);
        }

        // GET: Posts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        // GET: Posts/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Posts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Body,Date,Tag")] Post post)
        {
            if (ModelState.IsValid)
            {
                if (String.IsNullOrEmpty(post.Tag))
                {
                    post.Tags = null;
                }
                else
                {
                    var tags = post.Tag.Split(new char[] { ',', ' ' }, StringSplitOptions.RemoveEmptyEntries);
                    List<Tag> postTags = new List<Tag>();
                    foreach (var tag in tags)
                    {
                        Tag newTag = new Tag();
                        newTag.Title = tag;
                        List<Tag> search = new List<Tag>();
                        search.AddRange(db.Tags.Where(t => t.Title == newTag.Title));
                        if (search.Count() > 0)
                        {
                            var existingTag = db.Tags.Where(t => t.Title == newTag.Title);
                            postTags.AddRange(existingTag);

                        }
                        else
                        {
                            db.Tags.Add(newTag);
                            postTags.Add(newTag);
                        }
                    }
                    post.Tags = postTags;
                }
                post.Author = db.Users.FirstOrDefault(u=>u.UserName==User.Identity.Name);
                post.Date = DateTime.Now;
                db.Posts.Add(post);
                db.SaveChanges();
                this.AddNotification("Post created!",NotificationType.SUCCESS);
                return RedirectToAction("Index");
            }

            return View(post);
        }

        // GET: Posts/Edit/5
        [Authorize(Roles ="Administrators")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Administrators")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Body,Tag,Tags")] Post post)
        {
            if (ModelState.IsValid)
            {
                var currentPost = db.Posts.Include(p => p.Tags).Single(x => x.Id == post.Id);
                currentPost.Tags.Clear();
                currentPost.Tag = post.Tag;
                if (!String.IsNullOrEmpty(post.Tag))
                {
                    string[] tags = post.Tag.Split(new char[] { ',', ' ' }, StringSplitOptions.RemoveEmptyEntries).ToArray();
                    List<Tag> postTags = new List<Tag>();
                    foreach (var tag in tags)
                    {
                        Tag newTag = new Tag();
                        newTag.Title = tag;
                        List<Tag> search = new List<Tag>();
                        search.AddRange(db.Tags.Where(t => t.Title == newTag.Title));
                        if (search.Count() > 0)
                        {
                            var existingTag = db.Tags.Where(t => t.Title == newTag.Title);
                            postTags.AddRange(existingTag);

                        }
                        else
                        {
                            db.Tags.Add(newTag);
                            postTags.Add(newTag);
                        }
                        currentPost.Tags = postTags;
                    }
                }
                currentPost.Title = post.Title;
                currentPost.Body = post.Body;
                db.Entry(currentPost).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(post);
        }

        // GET: Posts/Delete/5
        [Authorize(Roles = "Administrators")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        // POST: Posts/Delete/5
        [Authorize(Roles = "Administrators")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Post post = db.Posts.Find(id);
            db.Comments.RemoveRange(post.Comments);
            post.Tags.Clear();  
            db.Posts.Remove(post);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        // GET: Posts/SinglePost/5
        public ActionResult SinglePost(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = GetPost(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        private Post GetPost(int? id)
        {
            return id.HasValue ? db.Posts.Include(p => p.Author).Include(t=>t.Tags).Where(x => x.Id == id).First() : new Post { Id = -1 };
        }


    }
}

WebStepBlog/Controllers/TagsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebStepBlog.Models;

namespace WebStepBlog.Controllers
{
    public class TagsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Tags
        public ActionResult Index()
        {
            var tags = db.Tags.Include(t => t.Posts).OrderByDescending(t=>t.Posts.Count).ToList();
            return View(tags);
        }

        public ActionResult PostsByTag(string tagName)
        {
            var tags = db.Tags.Where(tag=>tag.Title==tagName).Include(t => t.Posts.Select(a=>a.Author)).ToList();
            return View(tags);
        }

        // GET: Tags/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }

        // GET: Tags/Create
        [Authorize(Roles = "Administrators")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Tags/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Administrators")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title")] Tag tag)
        {
            if (ModelState.IsValid)
            {
                db.Tags.Add(tag);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tag);
        }

        // GET: Tags/Edit/5
        [Authorize(Roles = "Administrators")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }

        // POST: Tags/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Administrators")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title")] Tag tag)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tag).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tag);
        }

        // GET: Tags/Delete/5
        [Authorize(Roles = "Administrators")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }

        // POST: Tags/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Administrators")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tag tag = db.Tags.Find(id);
            db.Tags.Remove(tag);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebStepBlog/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h3>@ViewBag.Title.</h3>
<h3>@ViewBag.Message</h3>

<p>This is a blog for buying and selling cars and other vehicles from owners.</p>

WebStepBlog/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h3>@ViewBag.Title.</h3>
<h3>@ViewBag.Message</h3>

<address>
    <h3>    Manager   </h3> 
    <p>Glen B. Robertson</p>
    <abbr title="Phone">304-237-1944</abbr>
    <p>25 Ridge Rd, Webster, NY</p>
</address>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script><div style="overflow:hidden;height:325px;width:360px;">
    <div id="gmap_canvas" style="height:325px;width:360px;">
    <style>
        #gmap_canvas img {
            max-width: none !important;
            background: none !important;
        }
    </style><a class="google-map-code" href="http://www.map-embed.com" id="get-map-data">embed google map</a></div>
    <script type="text/javascript"> function init_map(){var myOptions = {zoom:14,center:new google.maps.LatLng(43.2122998,-77.42944890000001),mapTypeId: google.maps.MapTypeId.ROADMAP};map = new google.maps.Map(document.getElementById("gmap_canvas"), myOptions);marker = new google.maps.Marker({map: map,position: new google.maps.LatLng(43.2122998, -77.42944890000001)});infowindow = new google.maps.InfoWindow({content:"<b>Webstep Autos</b><br/>Ridge Rd 25<br/> Webster" });google.maps.event.addListener(marker, "click", function(){infowindow.open(map,marker);});infowindow.open(map,marker);}google.maps.event.addDomListener(window, 'load', init_map);</script>
    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>

WebStepBlog/Views/Home/Index.cshtml
@model IEnumerable<object>
@using PagedList;
@using PagedList.Mvc;
@using WebStepBlog.Classes

@{
    IPagedList<WebStepBlog.Models.Post> Posts = Model.ToList()[0] as IPagedList<WebStepBlog.Models.Post>;
    List<WebStepBlog.Models.Post> recentPosts = Model.ToList()[1] as List<WebStepBlog.Models.Post>;
    List<WebStepBlog.Models.Tag> tags = Model.ToList()[2] as List<WebStepBlog.Models.Tag>;
}

@{
    ViewBag.Title = "WebStep";
}

<div class="row">
    <div class="col-md-8">
        @foreach (var post in Posts)
        {
            <article class="post col-md-8" style="width:700px">
                <h4 class="title">@Html.ActionLink(@post.Title, "SinglePost", "Posts", new { id = post.Id }, null) </h4>
                <hr />
                <div>
                    Posted on <span class="glyphicon glyphicon-calendar"></span>    <i>@post.Date</i>
                    <i>
                        @if (post.Author != null)
                        {
                            @:by <span class="glyphicon glyphicon-user"></span> <i>@post.Author.FullName</i>
                        }
                    </i>
                    @if (post.Comments.Count == 0)
                    {
                        <div style="float:right">
                            <span class="glyphicon glyphicon-pencil"></span>                      
                            @Html.ActionLink("Leave a comment", "CreateComment", "Comments", new { id = post.Id }, null)
                        </div>
                    }
                    else if (post.Comments.Count == 1)
                    {
                        <div style="float:right">
                            <span class="glyphicon glyphicon-pencil"></span>
                            @Html.ActionLink(post.Comments.Count + " Comment", "CreateComment", "Comments", new { id = post.Id }, null)
                        </div>
                    }
                    else
                    {
                        <div style="float:right">
                            <span class="glyphicon glyphicon-pencil"></span>
                            @Html.ActionLink(post.Comments.Count + " Comments", "CreateComment", "Comments", new { id = post.Id }, null)
                        </div>
                    }
                </div>
                <hr />
                <div class="post-body">
                    <p>
                        @Html.Raw(Utils.CutText(post.Body, 200))
                        @if (post.Body.Length > 200)
                        {
                            <span style="float: right">@Html.ActionLink("Read More", "SinglePost", "Posts", new {id = post.Id}, null)</span>
                        }
                    </p>
                    @if (post.Tags.Count > 0)
                    {
                        <div class="post-tags">
                            <p class="glyphicon glyphicon-tag">
                                @foreach (var tag in post.Tags)
                                {
                                    <span class="tag index-tag">
                                        <strong>@Html.ActionLink(tag.Title, "PostsByTag", "Tags", new { tagName = tag.Title }, null)</strong>
                                    </span>
                                }
                            </p>
                        </div>
                    }                      
                </div>
            </article>
        }
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><strong>Recent Posts</strong>
                </h3>
            </div>
            @for (int i = 0; i < Math.Min(recentPosts.Count(), 5); i++)
            {
                <div class="panel-body">
                    <span class="glyphicon glyphicon-book"></span> @Html.ActionLink(recentPosts[i].Title, "SinglePost", "Posts", new { id = recentPosts[i].Id }, null)
                </div>
            }
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    <strong>Popular Tags</strong>
                </h3>
            </div>
            @for (int i = 0; i < Math.Min(tags.Count(), 5); i++)
            {
                <div class="panel-body">
                    <span class="glyphicon glyphicon-tag"></span>
                    @Html.ActionLink(tags[i].Title, "PostsByTag", "Tags", new { tagName = tags[i].Title }, null)
                </div>
            }
        </div>
    </div>
</div>
<div class="pager">@Html.PagedListPager(Posts, page => Url.Action("Index", new { page }), new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded, DisplayPageCountAndCurrentLocation = true })</div>